=== tree-sitter/tree-sitter/cli/src/generate/grammar-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "tree-sitter grammar specification",
  "type": "object",

  "required": ["name", "rules"],

  "additionalProperties": false,

  "properties": {
    "name": {
      "description": "the name of the grammar",
      "type": "string",
      "pattern": "^[a-zA-Z_]\\w*"
    },

    "rules": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z_]\\w*$": {
          "$ref": "#/definitions/rule"
        }
      },
      "additionalProperties": false
    },

    "extras": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/rule"
      }
    },

    "precedences": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/rule"
        }
      }
    },

    "externals": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/rule"
      }
    },

    "inline": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-zA-Z_]\\w*$"
      }
    },

    "conflicts": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^[a-zA-Z_]\\w*$"
        }
      }
    },

    "word": {
      "type": "string",
      "pattern": "^[a-zA-Z_]\\w*"
    },

    "supertypes": {
      "description": "A list of hidden rule names that should be considered supertypes in the generated node types file. See https://tree-sitter.github.io/tree-sitter/using-parsers#static-node-types.",
      "type": "array",
      "items": {
        "description": "the name of a rule in `rules` or `extras`",
        "type": "string"
      }
    }
  },

  "definitions": {
    "blank-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^BLANK$"
        }
      },
      "required": ["type"]
    },

    "string-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^STRING$"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "value"]
    },

    "pattern-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^PATTERN$"
        },
        "value": { "type": "string" }
      },
      "required": ["type", "value"]
    },

    "symbol-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^SYMBOL$"
        },
        "name": { "type": "string" }
      },
      "required": ["type", "name"]
    },

    "seq-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^SEQ$"
        },
        "members": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/rule"
          }
        }
      },
      "required": ["type", "members"]
    },

    "choice-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^CHOICE$"
        },
        "members": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/rule"
          }
        }
      },
      "required": ["type", "members"]
    },

    "alias-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^ALIAS$"
        },
        "value": {
          "type": "string"
        },
        "named": {
          "type": "boolean"
        },
        "content": {
          "$ref": "#/definitions/rule"
        }
      },
      "required": ["type", "named", "content", "value"]
    },

    "repeat-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^REPEAT$"
        },
        "content": {
          "$ref": "#/definitions/rule"
        }
      },
      "required": ["type", "content"]
    },

    "repeat1-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^REPEAT1$"
        },
        "content": {
          "$ref": "#/definitions/rule"
        }
      },
      "required": ["type", "content"]
    },

    "token-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^(TOKEN|IMMEDIATE_TOKEN)$"
        },
        "content": {
          "$ref": "#/definitions/rule"
        }
      },
      "required": ["type", "content"]
    },

    "field-rule": {
      "properties": {
        "name": { "type": "string" },
        "type": {
          "type": "string",
          "pattern": "^FIELD$"
        },
        "content": {
          "$ref": "#/definitions/rule"
        }
      },
      "required": ["name", "type", "content"]
    },

    "prec-rule": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "pattern": "^(PREC|PREC_LEFT|PREC_RIGHT|PREC_DYNAMIC)$"
        },
        "value": {
          "oneof": [
            { "type": "integer" },
            { "type": "string" }
          ]
        },
        "content": {
          "$ref": "#/definitions/rule"
        }
      },
      "required": ["type", "content", "value"]
    },

    "rule": {
      "oneOf": [
        { "$ref": "#/definitions/alias-rule" },
        { "$ref": "#/definitions/blank-rule" },
        { "$ref": "#/definitions/string-rule" },
        { "$ref": "#/definitions/pattern-rule" },
        { "$ref": "#/definitions/symbol-rule" },
        { "$ref": "#/definitions/seq-rule" },
        { "$ref": "#/definitions/choice-rule" },
        { "$ref": "#/definitions/repeat1-rule" },
        { "$ref": "#/definitions/repeat-rule" },
        { "$ref": "#/definitions/token-rule" },
        { "$ref": "#/definitions/field-rule" },
        { "$ref": "#/definitions/prec-rule" }
      ]
    }
  }
}

=== tree-sitter/tree-sitter/test/fixtures/test_grammars/inlined_aliased_rules/grammar.json
{
  "name": "inlined_aliased_rules",

  "extras": [
    {"type": "PATTERN", "value": "\\s"}
  ],

  "inline": [
    "expression"
  ],

  "rules": {
    "statement": {
      "type": "SEQ",
      "members": [
        {"type": "SYMBOL", "name": "expression"},
        {"type": "STRING", "value": ";"}
      ]
    },

    "expression": {
      "type": "CHOICE",
      "members": [
        {"type": "SYMBOL", "name": "call_expression"},
        {"type": "SYMBOL", "name": "member_expression"},
        {
          "type": "ALIAS",
          "value": "variable_name",
          "named": true,
          "content": {
            "type": "SYMBOL",
            "name": "identifier"
          }
        }
      ]
    },

    "call_expression": {
      "type": "PREC_LEFT",
      "value": 0,
      "content": {
        "type": "SEQ",
        "members": [
          {"type": "SYMBOL", "name": "expression"},
          {"type": "STRING", "value": "("},
          {"type": "SYMBOL", "name": "expression"},
          {"type": "STRING", "value": ")"}
        ]
      }
    },

    "member_expression": {
      "type": "PREC_LEFT",
      "value": 1,
      "content": {
        "type": "SEQ",
        "members": [
          {"type": "SYMBOL", "name": "expression"},
          {"type": "STRING", "value": "."},
          {
            "type": "ALIAS",
            "named": true,
            "value": "property_name",
            "content": {
              "type": "SYMBOL",
              "name": "identifier"
            }
          }
        ]
      }
    },

    "identifier": {"type": "PATTERN", "value": "[a-z]+"}
  }
}

=== tree-sitter/tree-sitter/tree-sitter-test/src/grammar.json
{
  "name": "test",
  "rules": {
    "file": {
      "type": "REPEAT",
      "content": {
        "type": "CHOICE",
        "members": [
          {
            "type": "SYMBOL",
            "name": "test"
          },
          {
            "type": "SYMBOL",
            "name": "_eol"
          }
        ]
      }
    },
    "test": {
      "type": "PREC_RIGHT",
      "value": 0,
      "content": {
        "type": "SEQ",
        "members": [
          {
            "type": "SYMBOL",
            "name": "header"
          },
          {
            "type": "ALIAS",
            "content": {
              "type": "SYMBOL",
              "name": "_body"
            },
            "named": true,
            "value": "input"
          },
          {
            "type": "ALIAS",
            "content": {
              "type": "SYMBOL",
              "name": "_dashes"
            },
            "named": true,
            "value": "separator"
          },
          {
            "type": "CHOICE",
            "members": [
              {
                "type": "ALIAS",
                "content": {
                  "type": "SYMBOL",
                  "name": "_body"
                },
                "named": true,
                "value": "output"
              },
              {
                "type": "BLANK"
              }
            ]
          }
        ]
      }
    },
    "_line": {
      "type": "PATTERN",
      "value": "[^\\r\\n]+"
    },
    "_body": {
      "type": "REPEAT1",
      "content": {
        "type": "CHOICE",
        "members": [
          {
            "type": "SYMBOL",
            "name": "_line"
          },
          {
            "type": "SYMBOL",
            "name": "_eol"
          }
        ]
      }
    },
    "header": {
      "type": "SEQ",
      "members": [
        {
          "type": "ALIAS",
          "content": {
            "type": "SYMBOL",
            "name": "_equals_begin"
          },
          "named": true,
          "value": "separator"
        },
        {
          "type": "ALIAS",
          "content": {
            "type": "SYMBOL",
            "name": "_line"
          },
          "named": true,
          "value": "name"
        },
        {
          "type": "SYMBOL",
          "name": "_eol"
        },
        {
          "type": "CHOICE",
          "members": [
            {
              "type": "SYMBOL",
              "name": "attributes"
            },
            {
              "type": "BLANK"
            }
          ]
        },
        {
          "type": "ALIAS",
          "content": {
            "type": "SYMBOL",
            "name": "_equals_end"
          },
          "named": true,
          "value": "separator"
        }
      ]
    },
    "attributes": {
      "type": "REPEAT1",
      "content": {
        "type": "CHOICE",
        "members": [
          {
            "type": "SYMBOL",
            "name": "attribute"
          },
          {
            "type": "SYMBOL",
            "name": "_eol"
          }
        ]
      }
    },
    "attribute": {
      "type": "CHOICE",
      "members": [
        {
          "type": "STRING",
          "value": ":skip"
        },
        {
          "type": "STRING",
          "value": ":error"
        },
        {
          "type": "STRING",
          "value": ":fail-fast"
        },
        {
          "type": "SYMBOL",
          "name": "_language"
        },
        {
          "type": "SYMBOL",
          "name": "_platform"
        }
      ]
    },
    "_language": {
      "type": "SEQ",
      "members": [
        {
          "type": "STRING",
          "value": ":language"
        },
        {
          "type": "STRING",
          "value": "("
        },
        {
          "type": "FIELD",
          "name": "language",
          "content": {
            "type": "ALIAS",
            "content": {
              "type": "SYMBOL",
              "name": "_lang"
            },
            "named": true,
            "value": "parameter"
          }
        },
        {
          "type": "STRING",
          "value": ")"
        }
      ]
    },
    "_platform": {
      "type": "SEQ",
      "members": [
        {
          "type": "STRING",
          "value": ":platform"
        },
        {
          "type": "STRING",
          "value": "("
        },
        {
          "type": "FIELD",
          "name": "platform",
          "content": {
            "type": "ALIAS",
            "content": {
              "type": "SYMBOL",
              "name": "_os"
            },
            "named": true,
            "value": "parameter"
          }
        },
        {
          "type": "STRING",
          "value": ")"
        }
      ]
    },
    "_lang": {
      "type": "TOKEN",
      "content": {
        "type": "REPEAT1",
        "content": {
          "type": "PATTERN",
          "value": "[\\w.-]"
        }
      }
    },
    "_os": {
      "type": "TOKEN",
      "content": {
        "type": "CHOICE",
        "members": [
          {
            "type": "STRING",
            "value": "linux"
          },
          {
            "type": "STRING",
            "value": "macos"
          },
          {
            "type": "STRING",
            "value": "ios"
          },
          {
            "type": "STRING",
            "value": "freebsd"
          },
          {
            "type": "STRING",
            "value": "dragonfly"
          },
          {
            "type": "STRING",
            "value": "netbsd"
          },
          {
            "type": "STRING",
            "value": "openbsd"
          },
          {
            "type": "STRING",
            "value": "solaris"
          },
          {
            "type": "STRING",
            "value": "android"
          },
          {
            "type": "STRING",
            "value": "windows"
          }
        ]
      }
    },
    "_eol": {
      "type": "PATTERN",
      "value": "[\\r\\n]|\\r\\n"
    }
  },
  "extras": [],
  "conflicts": [],
  "precedences": [],
  "externals": [
    {
      "type": "SYMBOL",
      "name": "_equals_begin"
    },
    {
      "type": "SYMBOL",
      "name": "_equals_end"
    },
    {
      "type": "SYMBOL",
      "name": "_dashes"
    }
  ],
  "inline": [],
  "supertypes": []
}

=== tree-sitter/tree-sitter/test/fixtures/test_grammars/dynamic_precedence/grammar.json
{
  "name": "dynamic_precedence",

  "conflicts": [
    ["expression", "type"]
  ],

  "extras": [
    {"type": "PATTERN", "value": "\\s"}
  ],

  "rules": {
    "program": {
      "type": "CHOICE",
      "members": [
        {"type": "SYMBOL", "name": "declaration"},
        {"type": "SYMBOL", "name": "expression"}
      ]
    },

    "expression": {
      "type": "PREC_LEFT",
      "value": 0,
      "content": {
        "type": "CHOICE",
        "members": [
          {
            "type": "SEQ",
            "members": [
              {"type": "SYMBOL", "name": "expression"},
              {"type": "STRING", "value": "*"},
              {"type": "SYMBOL", "name": "expression"}
            ]
          },
          {
            "type": "SYMBOL",
            "name": "identifier"
          }
        ]
      }
    },

    "declaration": {
      "type": "SEQ",
      "members": [
        {"type": "SYMBOL", "name": "type"},
        {"type": "SYMBOL", "name": "declarator"}
      ]
    },

    "declarator": {
      "type": "PREC_DYNAMIC",
      "value": 1,
      "content": {
        "type": "SEQ",
        "members": [
          {"type": "STRING", "value": "*"},
          {"type": "SYMBOL", "name": "identifier"}
        ]
      }
    },

    "type": {
      "type": "SYMBOL",
      "name": "identifier"
    },

    "identifier": {
      "type": "PATTERN",
      "value": "[a-zA-Z]+"
    }
  }
}

=== tree-sitter/tree-sitter/test/fixtures/test_grammars/inverted_external_token/grammar.json
{
  "name": "inverted_external_token",

  "externals": [
    {"type": "SYMBOL", "name": "line_break"}
  ],

  "extras": [
    {"type": "PATTERN", "value": "\\s"}
  ],

  "rules": {
    "program": {
      "type": "REPEAT",
      "content": {
        "type": "SYMBOL",
        "name": "statement"
      }
    },

    "statement": {
      "type": "SEQ",
      "members": [
        {"type": "SYMBOL", "name": "_expression"},
        {"type": "SYMBOL", "name": "line_break"}
      ]
    },

    "_expression": {
      "type": "CHOICE",
      "members": [
        {"type": "SYMBOL", "name": "identifier"},
        {"type": "SYMBOL", "name": "member_expression"}
      ]
    },

    "member_expression": {
      "type": "PREC_LEFT",
      "value": 0,
      "content": {
        "type": "SEQ",
        "members": [
          {"type": "SYMBOL", "name": "_expression"},
          {"type": "STRING", "value": "."},
          {"type": "SYMBOL", "name": "identifier"}
        ]
      }
    },

    "identifier": {
      "type": "PATTERN",
      "value": "[a-z]+"
    }
  }
}

=== tree-sitter/tree-sitter/test/fixtures/test_grammars/external_tokens/grammar.json
{
  "name": "external_tokens",

  "externals": [
    {"type": "SYMBOL", "name": "_percent_string"},
    {"type": "SYMBOL", "name": "_percent_string_start"},
    {"type": "SYMBOL", "name": "_percent_string_end"}
  ],

  "extras": [
    {"type": "PATTERN", "value": "\\s"}
  ],

  "rules": {
    "expression": {
      "type": "CHOICE",
      "members": [
        {"type": "SYMBOL", "name": "string"},
        {"type": "SYMBOL", "name": "sum"},
        {"type": "SYMBOL", "name": "identifier"}
      ]
    },

    "sum": {
      "type": "PREC_LEFT",
      "value": 0,
      "content": {
        "type": "SEQ",
        "members": [
          {"type": "SYMBOL", "name": "expression"},
          {"type": "STRING", "value": "+"},
          {"type": "SYMBOL", "name": "expression"}
        ]
      }
    },

    "string": {
      "type": "CHOICE",
      "members": [
        {"type": "SYMBOL", "name": "_percent_string"},
        {
          "type": "SEQ",
          "members": [
            {"type": "SYMBOL", "name": "_percent_string_start"},
            {"type": "SYMBOL", "name": "expression"},
            {"type": "SYMBOL", "name": "_percent_string_end"}
          ]
        }
      ]
    },

    "identifier": {
      "type": "PATTERN",
      "value": "[a-z]+"
    }
  }
}
